# Generated by Django 5.0.1 on 2024-01-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_task_created_at_alter_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('housing', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('transportation', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('utilities', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('food', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('restaurant', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('groceries', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('clothing', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('entertainment', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('travel', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('internet', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mob_internet', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
    ]
