# Generated by Django 5.0.1 on 2024-01-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
